# Generated by Django 5.2.9 on 2025-12-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('sales_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('categories', models.JSONField()),
                ('other_category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=200)),
                ('catalog_url', models.URLField(blank=True, null=True)),
                ('catalog_files', models.JSONField(blank=True, null=True)),
                ('moq', models.CharField(max_length=50)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('other_certs', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_intent', models.JSONField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
